# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=80)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(choices=[('SU', 'SupUser'), ('CU', 'CommonUser')], default='CU', max_length=2)),
                ('group', models.ManyToManyField(to='auser.UserGroup')),
            ],
        ),
    ]
