# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='passwd',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
