# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0003_auto_20170610_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200)),
                ('ipaddr', models.GenericIPAddressField(unique=True)),
                ('IDC', models.CharField(blank=True, max_length=200, null=True)),
                ('OS', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_num', models.SmallIntegerField(blank=True, max_length=10, null=True)),
                ('mem_info', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('hdd_type', models.CharField(choices=[('hdd', 'HDD'), ('ssd', 'SSD')], default='hdd', max_length=2)),
                ('hdd_num', models.SmallIntegerField(blank=True, max_length=200, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssestGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostgroupname', models.CharField(max_length=200)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='assest',
            name='assestgroup',
            field=models.ManyToManyField(to='auser.AssestGroup'),
        ),
    ]
