# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0004_auto_20170612_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assest',
            name='cpu_num',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assest',
            name='hdd_num',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assest',
            name='mem_info',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
