# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0006_auto_20170612_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='assest',
            name='passwd_key',
            field=models.CharField(default='123456', max_length=200),
        ),
        migrations.AddField(
            model_name='assest',
            name='port',
            field=models.CharField(default='22', max_length=100),
        ),
        migrations.AlterField(
            model_name='assest',
            name='hostname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
