# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0010_auto_20170613_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('assest', models.ManyToManyField(to='auser.Assest')),
                ('assestgroup', models.ManyToManyField(to='auser.AssestGroup')),
                ('user', models.ManyToManyField(to='auser.UserName')),
                ('usergroup', models.ManyToManyField(to='auser.UserGroup')),
            ],
        ),
    ]
